import { rmSync, existsSync } from 'node:fs'
import path from 'node:path'
import type { Command } from 'commander'
import chalk from 'chalk'

interface ClearResult {
  /** Path relative to the app root, e.g. `bootstrap/cache/` */
  target:  string
  /** What the target holds — shown next to the checkmark */
  label:   string
  cleared: boolean
}

/**
 * Remove the framework's filesystem caches. Everything here is regenerated
 * automatically: the provider manifest self-heals at boot, and Vite rebuilds
 * its dep-optimizer cache on the next dev server start.
 *
 * Deliberately NOT cleared: `.rudder/types/` and `pages/__view/` (committed,
 * regenerated by scanners — wiping them breaks a fresh-clone typecheck) and
 * `dist/` (build output, that's `pnpm clean`'s job).
 */
export function clearFrameworkCaches(cwd: string): ClearResult[] {
  const targets: Array<Omit<ClearResult, 'cleared'>> = [
    { target: 'bootstrap/cache/',    label: 'provider manifest (self-heals at boot)' },
    { target: 'node_modules/.vite/', label: 'Vite dep-optimizer cache' },
  ]

  return targets.map(({ target, label }) => {
    const abs = path.join(cwd, target)
    if (!existsSync(abs)) return { target, label, cleared: false }
    rmSync(abs, { recursive: true, force: true })
    return { target, label, cleared: true }
  })
}

/** Print one line per target — ✔ cleared / dim already-empty. */
export function reportClearResults(results: ClearResult[]): void {
  for (const r of results) {
    if (r.cleared) {
      console.log(chalk.green('  ✔ Cleared:'), chalk.cyan(r.target), chalk.dim(`— ${r.label}`))
    } else {
      console.log(chalk.dim(`  - ${r.target} already empty`))
    }
  }
}

/**
 * `rudder optimize:clear` — Laravel-parity name for "wipe the framework's
 * filesystem caches". Skip-boot: it must work when a corrupt cache is the
 * reason the app can't boot.
 */
export function optimizeClearCommand(program: Command): void {
  program
    .command('optimize:clear')
    .description('Remove framework filesystem caches (provider manifest, Vite dep-optimizer cache)')
    .action(() => {
      reportClearResults(clearFrameworkCaches(process.cwd()))
    })
}
