// AUTO-GENERATED by @rudderjs/orm — do not edit.
// Source: the migrated database schema (run `rudder schema:types` or `migrate`).
import '@rudderjs/orm'

declare module '@rudderjs/orm' {
  interface SchemaRegistry {
    budgetUsage: {
      id: number
      userId: string
      period: string
      periodKey: string
      spent: number
      createdAt: string
      updatedAt: string
    }
    comments: {
      id: number
      body: string
      commentableId: number
      commentableType: string
      createdAt: string
    }
    notification: {
      id: number
      notifiable_id: string
      notifiable_type: string
      type: string
      data: string
      read_at: string | null
      created_at: string
      updated_at: string
    }
    oAuthAccessToken: {
      id: number
      userId: string | null
      clientId: string
      name: string | null
      scopes: string
      revoked: number
      expiresAt: string
      createdAt: string
    }
    oAuthAuthCode: {
      id: number
      tokenHash: string
      userId: string
      clientId: string
      scopes: string
      revoked: number
      expiresAt: string
      redirectUri: string | null
      codeChallenge: string | null
      codeChallengeMethod: string | null
    }
    oAuthClient: {
      id: number
      name: string
      secret: string | null
      redirectUris: unknown
      grantTypes: unknown
      scopes: unknown
      confidential: number
      revoked: number
      createdAt: string
      updatedAt: string
    }
    oAuthDeviceCode: {
      id: number
      clientId: string
      userCodeHash: string
      deviceCodeHash: string
      scopes: string
      userId: string | null
      approved: number | null
      interval: number
      expiresAt: string
      lastPolledAt: string | null
      createdAt: string
    }
    oAuthRefreshToken: {
      id: number
      tokenHash: string
      accessTokenId: string
      familyId: string | null
      revoked: number
      expiresAt: string
    }
    paddleCustomer: {
      id: number
      paddleId: string | null
      billableId: string
      billableType: string
      name: string | null
      email: string | null
      trialEndsAt: string | null
      createdAt: string
      updatedAt: string
    }
    paddleSubscription: {
      id: number
      billableId: string
      billableType: string
      type: string
      paddleId: string
      paddleStatus: string
      paddleProductId: string | null
      trialEndsAt: string | null
      pausedAt: string | null
      endsAt: string | null
      createdAt: string
      updatedAt: string
    }
    paddleSubscriptionItem: {
      id: number
      subscriptionId: string
      productId: string
      priceId: string
      status: string
      quantity: number
      createdAt: string
      updatedAt: string
    }
    paddleTransaction: {
      id: number
      paddleId: string
      paddleCustomerId: string | null
      paddleSubscriptionId: string | null
      billableId: string
      billableType: string
      invoiceNumber: string | null
      status: string
      total: string
      tax: string
      currency: string
      billedAt: string | null
      createdAt: string
      updatedAt: string
    }
    paddleWebhookLog: {
      id: number
      eventId: string
      eventType: string
      processedAt: string
    }
    posts: {
      id: number
      title: string
      createdAt: string
    }
    taggables: {
      tagId: number
      taggableId: number
      taggableType: string
    }
    tags: {
      id: number
      name: string
    }
    todos: {
      id: number
      title: string
      completed: boolean
      createdAt: Date
      updatedAt: Date
    }
    userMemory: {
      id: number
      userId: string
      fact: string
      tags: string | null
      score: number | null
      embedding: Uint8Array | null
      createdAt: string
      updatedAt: string
    }
    users: {
      id: number
      name: string
      email: string
      password: string | null
      emailVerifiedAt: string | null
      image: string | null
      role: string
      rememberToken: string | null
      createdAt: string
      updatedAt: string
    }
    videos: {
      id: number
      url: string
      createdAt: string
    }
  }
}
