import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

export interface PackageEntry {
  name: string
  shortName: string
  hasGuideline: boolean
}

export interface SkillSummary {
  name: string
  description?: string
  trigger?: string
  skip?: string
  appliesTo?: string[]
}

export interface GenerateClaudeMdInput {
  cwd: string
  packages: PackageEntry[]
  skills: SkillSummary[]
  nodeVersion?: string
}

const MCP_TOOLS: ReadonlyArray<{ name: string; summary: string }> = [
  { name: 'app_info',         summary: 'installed `@rudderjs/*` versions, Node version, package manager' },
  { name: 'db_schema',        summary: 'parsed Prisma schema models + raw `.prisma` source' },
  { name: 'route_list',       summary: 'registered HTTP routes (method, path, middleware, source file)' },
  { name: 'model_list',       summary: 'ORM models in `app/Models/` with tables + fields' },
  { name: 'config_get',       summary: 'read `config/*.ts` files by key' },
  { name: 'db_query',         summary: 'read-only `SELECT` queries against the project DB' },
  { name: 'last_error',       summary: 'most recent entries from `storage/logs/`' },
  { name: 'read_logs',        summary: 'log entries filtered by level + search term' },
  { name: 'browser_logs',     summary: 'browser console logs from the Vite dev server' },
  { name: 'get_absolute_url', summary: 'convert a relative path to an absolute URL using `APP_URL`' },
  { name: 'search_docs',      summary: 'keyword search across installed `@rudderjs/*` package docs' },
  { name: 'commands_list',    summary: 'all `rudder` commands (built-in + package + user)' },
  { name: 'command_run',      summary: 'execute a `rudder` command and capture stdout/stderr/exit' },
]

export function generateClaudeMd(input: GenerateClaudeMdInput): string {
  const out: string[] = []

  out.push('<rudderjs-boost-guidelines>')
  out.push('')
  out.push('=== foundation rules ===')
  out.push('')
  out.push('# RudderJS Boost Guidelines')
  out.push('')
  out.push('These guidelines are generated by `@rudderjs/boost` from your installed')
  out.push('`@rudderjs/*` packages. Treat them as the project\'s source of truth for')
  out.push('framework patterns.')
  out.push('')

  // Foundational Context
  out.push('## Foundational Context')
  out.push('')
  out.push(`- node — ${input.nodeVersion ?? process.version}`)
  for (const pkg of input.packages) {
    const v = resolvePackageVersion(input.cwd, pkg.name)
    out.push(`- ${pkg.name}${v ? ` — ${v}` : ''}`)
  }
  out.push('')

  // Per-package guidelines — pointers, not content
  if (input.packages.some(p => p.hasGuideline)) {
    out.push('## Per-package guidelines')
    out.push('')
    out.push('For framework patterns specific to a package, open the matching guideline:')
    out.push('')
    for (const pkg of input.packages) {
      if (!pkg.hasGuideline) continue
      out.push(`- \`${pkg.name}\` → \`.ai/guidelines/${pkg.shortName}.md\``)
    }
    out.push('')
  }

  // === boost rules ===
  out.push('=== boost rules ===')
  out.push('')
  out.push('# Boost MCP Tools')
  out.push('')
  out.push('When you need information about this project, **prefer Boost MCP tools')
  out.push('over re-deriving from the filesystem.** Tools are exposed by the')
  out.push('`rudderjs-boost` MCP server (registered in `.mcp.json`).')
  out.push('')
  for (const tool of MCP_TOOLS) {
    out.push(`- \`${tool.name}\` — ${tool.summary}`)
  }
  out.push('')
  out.push('Per-package guidelines are also available as MCP resources:')
  out.push('`guidelines://all` (concatenated) or `guidelines://<package-short-name>`')
  out.push('(e.g. `guidelines://orm`).')
  out.push('')

  // === skills activation ===
  if (input.skills.length > 0) {
    out.push('=== skills activation ===')
    out.push('')
    out.push('# Skills Activation')
    out.push('')
    out.push('Skills live in `.ai/skills/`. **Load a skill only when its trigger')
    out.push('matches** — they\'re scoped knowledge modules, not always-on context.')
    out.push('')
    for (const skill of input.skills) {
      out.push(formatSkillActivation(skill))
    }
    out.push('')
  }

  out.push('</rudderjs-boost-guidelines>')
  out.push('')

  return out.join('\n')
}

function formatSkillActivation(skill: SkillSummary): string {
  const trigger = skill.trigger ?? skill.description ?? 'working with the skill\'s subject area'
  const parts = [`- \`${skill.name}\` — **ACTIVATE when:** ${trigger.replace(/\.$/, '')}.`]
  if (skill.skip) {
    parts.push(` **SKIP when:** ${skill.skip.replace(/\.$/, '')}.`)
  }
  return parts.join('')
}

function resolvePackageVersion(cwd: string, packageName: string): string | null {
  const pkgPath = join(cwd, 'node_modules', packageName, 'package.json')
  if (!existsSync(pkgPath)) return null
  try {
    const raw = readFileSync(pkgPath, 'utf-8')
    const parsed = JSON.parse(raw) as { version?: string }
    return parsed.version ?? null
  } catch {
    return null
  }
}
