// AUTO-GENERATED by @rudderjs/vite — overwrite freely to customize.
// Wires the page-context enhancer registry so packages can inject typed
// per-request data into pageContext (e.g. `pageContext.user` from @rudderjs/auth).
export { onCreatePageContext } from '@rudderjs/vite/hooks/onCreatePageContext'
