export { createRegistry } from './BaseRegistry.js'
export { FormRegistry } from './FormRegistry.js'
export { TableRegistry } from './TableRegistry.js'
export { StatsRegistry } from './StatsRegistry.js'
export { TabsRegistry } from './TabsRegistry.js'
export { ComputeRegistry } from './ComputeRegistry.js'
export { DashboardRegistry } from './DashboardRegistry.js'
export { PanelRegistry } from './PanelRegistry.js'
export { editorRegistry } from './EditorRegistry.js'
export type { RichContentEditorProps, CollaborativePlainTextProps } from './EditorRegistry.js'
export { registerField, getField, registerElement, getElement, onElementChange, registerLazyElement, getLazyElement } from './ComponentRegistry.js'
export { registerResolver, getResolver } from './ResolverRegistry.js'
