// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Forwards controller-supplied viewProps to client hydration. viewHeaders stays
// server-only (read by +headersResponse) — never serialized to the client.
import type { Config } from 'vike/types'

export default {
  passToClient: ['viewProps'],
} satisfies Config
