// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Source: `export const prerender = [...] | (...) => ...` in App/Views/Demos/PrerenderDynamic.tsx
import type { OnBeforePrerenderStartAsync } from 'vike/types'
import { prerender as source } from 'App/Views/Demos/PrerenderDynamic.tsx'

export const onBeforePrerenderStart: OnBeforePrerenderStartAsync<unknown> =
  async () => (typeof source === 'function' ? await source() : source)
