// AUTO-GENERATED by @rudderjs/vite — do not edit.
// The config/index.ts default export → typed config('section.key') autocomplete.
// Re-generated on every scan. Mirrors the hand-written augmentation apps used
// to add to @rudderjs/core: interface AppConfig extends typeof configs {}.
type RudderAppConfig = (typeof import('../../config/index.js'))['default']
declare module '@rudderjs/core' {
  interface AppConfig extends RudderAppConfig {}
}
export {}
