// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Maps named-route ids → URL patterns for typed route() calls.
// Re-generated on every scan; only routes with a literal path AND literal name
// at the call site are picked up. Hand-augment RouteRegistry yourself for
// runtime-registered routes (e.g. registerAuthRoutes from @rudderjs/auth).
declare module '@rudderjs/router' {
  interface RouteRegistry {
    'demos.index': '/demos'
    'health': '/api/health'
    'widgets.update': '/api/widgets/:id'
  }
}
export {}
