/**
 * config barrel scanner — emits an `AppConfig` augmentation so `config('…')`
 * calls autocomplete (and type-check) the app's own config sections.
 *
 * The TYPE machinery already lives in `@rudderjs/core` (`config.ts`): `config()`
 * is typed over `Paths<AppConfig>`, but `AppConfig` is an empty interface until
 * the app augments it. Apps used to hand-write
 *
 *   declare module '@rudderjs/core' {
 *     interface AppConfig extends typeof configs {}
 *   }
 *
 * This scanner generates exactly that, mirroring the typed-env scanner.
 *
 * Source of truth: the app's `config/index.ts` barrel (RudderJS convention —
 * the default-exported object of named config sections). The emit references it
 * by `import type`, so the registry always reflects the live shape without this
 * scanner parsing any config file. Emit is a single, content-independent file —
 * the only states are "barrel present → emit" and "barrel gone → remove the
 * stale emit" (symmetric shrink, like the env registry).
 *
 * Output: `.rudder/types/config.d.ts` (see `rudder-dir.ts`).
 */

import fs from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'
import { CONFIG_DTS, ensureRudderReadme } from './rudder-dir.js'

/** App-relative path to the config barrel that drives the augmentation. */
const CONFIG_BARREL = path.join('config', 'index.ts')

/**
 * Import specifier from the emit location (`.rudder/types/config.d.ts`) to the
 * app's config barrel. Both ends are fixed RudderJS conventions, so this is a
 * constant — two levels up out of `.rudder/types/`, then `config/index.js`.
 */
const CONFIG_IMPORT = '../../config/index.js'

/**
 * The `AppConfig` augmentation source. Constant text: the app's config shape is
 * pulled in by `import type`, resolved by `tsc` from the emit location — the
 * scanner never reads the config files themselves.
 *
 * An `interface` can't `extends` an indexed-access type directly
 * (`TS2499`), so the default export is first bound to a module-local alias.
 */
export function configRegistrySource(): string {
  return `// AUTO-GENERATED by @rudderjs/vite — do not edit.
// The config/index.ts default export → typed config('section.key') autocomplete.
// Re-generated on every scan. Mirrors the hand-written augmentation apps used
// to add to @rudderjs/core: interface AppConfig extends typeof configs {}.
type RudderAppConfig = (typeof import('${CONFIG_IMPORT}'))['default']
declare module '@rudderjs/core' {
  interface AppConfig extends RudderAppConfig {}
}
export {}
`
}

function writeIfChanged(file: string, contents: string): boolean {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  let existing: string | null = null
  try {
    existing = fs.readFileSync(file, 'utf8')
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err
  }
  if (existing === contents) return false
  fs.writeFileSync(file, contents)
  return true
}

// ─── One-shot sync (CLI surface) ──────────────────────────

export interface ConfigSyncResult {
  barrelExists: boolean
}

/**
 * One-shot emit, runnable outside Vite (the `config:sync` command, CI scripts).
 * Idempotent — read-compare-then-write. A missing `config/index.ts` removes any
 * stale emit instead of leaving a registry that augments against a barrel that
 * no longer exists (which would fail `tsc`).
 */
export function syncConfigFromDisk(cwd: string = process.cwd()): ConfigSyncResult {
  const barrel  = path.join(cwd, CONFIG_BARREL)
  const outFile = path.join(cwd, CONFIG_DTS)

  if (!fs.existsSync(barrel)) {
    try {
      fs.rmSync(outFile, { force: true })
    } catch { /* best effort */ }
    return { barrelExists: false }
  }

  writeIfChanged(outFile, configRegistrySource())
  ensureRudderReadme(cwd)
  return { barrelExists: true }
}

// ─── Plugin ────────────────────────────────────────────────

export function configScannerPlugin(): Plugin {
  const cwd    = process.cwd()
  const barrel = path.join(cwd, CONFIG_BARREL)

  // Eager sync at construction — same pattern as the env/routes scanners, so
  // the registry exists before the first tsc/IDE touch in a fresh dev session.
  syncConfigFromDisk(cwd)

  return {
    name: 'rudderjs:config-scanner',
    buildStart() { syncConfigFromDisk(cwd) },
    configureServer(server) {
      // Watch the barrel itself; emit/remove as it appears or disappears. The
      // emit content is barrel-independent (it references the shape via import
      // type), so edits to individual config/*.ts files need no re-emit — tsc
      // re-resolves the import. The emit target (.rudder/types/) sits outside
      // the re-boot watcher's dirs, so the write never chains a re-bootstrap.
      server.watcher.add(barrel)
      const onChange = (file: string): void => {
        if (file === barrel) syncConfigFromDisk(cwd)
      }
      server.watcher.on('add',    onChange)
      server.watcher.on('change', onChange)
      server.watcher.on('unlink', onChange)
    },
  }
}
