/**
 * .env.example scanner — parses the app's `.env.example` and emits an
 * `EnvRegistry` augmentation so `Env.get('…')` calls autocomplete the
 * declared keys.
 *
 * `.env.example` is the source of truth ON PURPOSE — it's the committed
 * contract of which keys the app expects. `.env` itself is secret, varies
 * per machine, and is absent in CI, so generating from it would produce a
 * registry that differs per checkout. (Same reasoning as typed models
 * generating from migrations, not from a hand-edited file.)
 *
 * Parse rules (v1, deliberately simple):
 * - `KEY=...` and `export KEY=...` lines declare a key.
 * - `# KEY=...` commented lines do NOT — a commented-out example
 *   (`# OPENAI_API_KEY=`) is an optional suggestion, not a declared key.
 * - All values are typed `string` (runtime truth; no value parsing).
 *
 * Output: `.rudder/types/env.d.ts` (see `rudder-dir.ts`). No `.env.example`
 * → any stale emit is removed (symmetric shrink, like the views registry).
 */

import fs from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'
import { ENV_DTS, ensureRudderReadme } from './rudder-dir.js'

const EXAMPLE_FILE = '.env.example'

/** One declared key + its example value (used by `env:sync --fix`). */
export interface DeclaredEnvKey {
  key:  string
  /** The full source line, e.g. `DATABASE_URL="file:./dev.db"`. */
  line: string
}

// `KEY=` / `export KEY=` at line start. Key charset matches dotenv's.
const ENV_LINE_RE = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/

/** Parse dotenv-format text into its declared keys (first-write-wins). */
export function parseEnvKeys(text: string): DeclaredEnvKey[] {
  const seen = new Map<string, DeclaredEnvKey>()
  for (const raw of text.split('\n')) {
    const line = raw.replace(/\r$/, '')
    if (/^\s*#/.test(line)) continue
    const m = ENV_LINE_RE.exec(line)
    if (!m) continue
    const key = m[1]!
    if (!seen.has(key)) seen.set(key, { key, line: line.trim() })
  }
  return [...seen.values()]
}

export function envRegistrySource(keys: DeclaredEnvKey[]): string {
  const entries = keys.map(k => `    '${k.key}': string`).join('\n')
  const body = entries ? `\n${entries}\n  ` : '\n  '

  return `// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Keys declared in .env.example → typed Env.get() autocomplete.
// Re-generated on every scan. Keys only your machine's .env carries are
// deliberately absent — .env.example is the committed contract.
declare module '@rudderjs/support' {
  interface EnvRegistry {${body}}
}
export {}
`
}

function writeIfChanged(file: string, contents: string): boolean {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  let existing: string | null = null
  try {
    existing = fs.readFileSync(file, 'utf8')
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err
  }
  if (existing === contents) return false
  fs.writeFileSync(file, contents)
  return true
}

// ─── One-shot sync (CLI surface) ──────────────────────────

export interface EnvSyncResult {
  exampleExists: boolean
  keyCount:      number
}

/**
 * One-shot parse + emit, runnable outside Vite (the `env:sync` command, CI
 * scripts). Idempotent — read-compare-then-write. A missing `.env.example`
 * removes any stale emit instead of leaving a registry that types keys the
 * contract no longer declares.
 */
export function syncEnvFromDisk(cwd: string = process.cwd()): EnvSyncResult {
  const example = path.join(cwd, EXAMPLE_FILE)
  const outFile = path.join(cwd, ENV_DTS)

  let text: string | null = null
  try {
    text = fs.readFileSync(example, 'utf8')
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err
  }

  if (text === null) {
    try {
      fs.rmSync(outFile, { force: true })
    } catch { /* best effort */ }
    return { exampleExists: false, keyCount: 0 }
  }

  const keys = parseEnvKeys(text)
  writeIfChanged(outFile, envRegistrySource(keys))
  ensureRudderReadme(cwd)
  return { exampleExists: true, keyCount: keys.length }
}

// ─── Plugin ────────────────────────────────────────────────

export function envScannerPlugin(): Plugin {
  const cwd     = process.cwd()
  const example = path.join(cwd, EXAMPLE_FILE)

  // Eager sync at construction — same pattern as the routes scanner, so the
  // registry exists before the first tsc/IDE touch in a fresh dev session.
  syncEnvFromDisk(cwd)

  return {
    name: 'rudderjs:env-scanner',
    buildStart() { syncEnvFromDisk(cwd) },
    configureServer(server) {
      // Watch the example file itself; re-emit on edits. The emit target
      // (.rudder/types/) sits outside the re-boot watcher's dirs, so the
      // write never chains a re-bootstrap.
      server.watcher.add(example)
      const onChange = (file: string): void => {
        if (file === example) syncEnvFromDisk(cwd)
      }
      server.watcher.on('add',    onChange)
      server.watcher.on('change', onChange)
      server.watcher.on('unlink', onChange)
    },
  }
}
