/**
 * `.rudder/` — the committed home for framework-generated files.
 *
 * Generated type registries used to live next to their domain
 * (`pages/__view/registry.d.ts`, `routes/__registry.d.ts`,
 * `app/Models/__schema/registry.d.ts`). That kept each one discoverable but
 * scattered three machine-written files across three user-owned directories.
 * They now consolidate under `.rudder/types/` — one obviously-generated,
 * committed directory with room for future artifacts (the typed-env
 * `env.d.ts` is next).
 *
 * Only the pure `.d.ts` augmentations moved. The Vike page stubs stay in
 * `pages/__view/` — they're pinned by Vike's filesystem routing.
 *
 * The models registry (`types/models.d.ts`) is emitted by
 * `@rudderjs/database`'s schema-types generator, which cannot share code with
 * this package (no common workspace dependency). Its path is duplicated
 * there — `packages/database/src/native/schema/schema-types.ts` — keep the
 * two in sync. This package owns `README.md` since the Vite scanners run in
 * every app's dev/build.
 */

import fs from 'node:fs'
import path from 'node:path'

export const RUDDER_DIR       = '.rudder'
export const RUDDER_TYPES_DIR = path.join(RUDDER_DIR, 'types')

/** App-relative emit path for the typed-route registry. */
export const ROUTES_DTS = path.join(RUDDER_TYPES_DIR, 'routes.d.ts')
/** App-relative emit path for the typed-view registry. */
export const VIEWS_DTS  = path.join(RUDDER_TYPES_DIR, 'views.d.ts')

const README = `# .rudder/ — generated by RudderJS

Machine-written. Don't edit anything here by hand — every file is rewritten
by its generator. Commit this directory: the type registries keep \`tsc\`
green on fresh clones and in CI without a generate step.

| File | What it types | Regenerated by |
|---|---|---|
| \`types/views.d.ts\` | \`view('id', props)\` — view id → exported \`Props\` | views scanner (dev/build) or \`rudder view:sync\` |
| \`types/routes.d.ts\` | \`route(name, params)\` — route name → URL pattern | routes scanner (dev/build) or \`rudder routes:sync\` |
| \`types/models.d.ts\` | \`Model.for<'table'>()\` — column types from the migrated schema (native engine) | \`rudder migrate\` or \`rudder schema:types\` |

If \`tsc\` can't see these augmentations, add \`".rudder/**/*"\` to your
\`tsconfig.json\` \`include\` array (dot-directories are invisible to \`**/*\`
globs and to bare-directory includes). \`rudder doctor\` checks this.
`

/**
 * Write `.rudder/README.md` (idempotent read-compare-write). Called from the
 * scanners' sync paths so the directory is self-describing from the moment
 * anything lands in it.
 */
export function ensureRudderReadme(cwd: string): void {
  const file = path.join(cwd, RUDDER_DIR, 'README.md')
  fs.mkdirSync(path.dirname(file), { recursive: true })
  let existing: string | null = null
  try {
    existing = fs.readFileSync(file, 'utf8')
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err
  }
  if (existing !== README) fs.writeFileSync(file, README)
}
