/**
 * app/Views scanner — generates virtual Vike pages for files in `app/Views/**`.
 *
 * For every `app/Views/Dashboard.tsx` we emit:
 *
 *   pages/__view/dashboard/+Page.tsx     → re-exports user's view + reads viewProps from pageContext
 *   pages/__view/dashboard/+route.ts     → pins the route to /__view/dashboard
 *
 * The generated `pages/__view/` directory is gitignored. The plugin watches
 * `app/Views/**` and regenerates on add/remove/rename.
 *
 * `view('dashboard', props)` from a router handler then resolves to URL
 * `/__view/dashboard` and Vike renders the page with `pageContext.viewProps`.
 */

import fs from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'

const VIEW_EXTENSIONS = ['.tsx', '.jsx']

interface DiscoveredView {
  /** Dot-notation id, e.g. `'dashboard'` or `'users.show'` */
  id:           string
  /** Absolute path to the user's view file */
  absPath:      string
  /** Path relative to the playground root, with `App/` prefix for the alias */
  importPath:   string
  /** Output directory for the generated Vike page (absolute) */
  outDir:       string
}

/** Convert `Dashboard.tsx` → `dashboard`, `Users/Show.tsx` → `users.show` */
function fileToId(relPath: string): string {
  const noExt = relPath.replace(/\.(tsx|jsx)$/i, '')
  return noExt
    .split(path.sep)
    .map(seg => seg.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase())
    .join('.')
}

function walk(dir: string, base = dir): string[] {
  if (!fs.existsSync(dir)) return []
  const out: string[] = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      out.push(...walk(full, base))
    } else if (VIEW_EXTENSIONS.some(e => entry.name.toLowerCase().endsWith(e))) {
      out.push(path.relative(base, full))
    }
  }
  return out
}

function discover(viewsRoot: string, pagesRoot: string): DiscoveredView[] {
  return walk(viewsRoot).map(rel => {
    const id      = fileToId(rel)
    const absPath = path.join(viewsRoot, rel)
    // Use the App/ alias (already configured in @rudderjs/vite) so the
    // generated import is portable across machines.
    const importPath = `App/Views/${rel.replace(/\\/g, '/')}`
    const outDir     = path.join(pagesRoot, '__view', ...id.split('.'))
    return { id, absPath, importPath, outDir }
  })
}

function pageFileSource(view: DiscoveredView): string {
  return `// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Source: ${view.importPath}
import ViewComponent from '${view.importPath}'
import { usePageContext } from 'vike-react/usePageContext'

// Cast to a permissive component type — controller-supplied props are validated
// at the call site (view('id', props)), not in this generated stub.
const View = ViewComponent as unknown as (props: Record<string, unknown>) => JSX.Element

export default function Page() {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown> }
  const props = ctx.viewProps ?? {}
  return <View {...props} />
}
`
}

/**
 * No-op +data hook. Its presence forces Vike's client router to recognize
 * this page as having a server-side hook (`hasServerOnlyHook: true`), which
 * makes it fetch `pageContext.json` on every SPA navigation. Without this,
 * navigating from a regular Vike page into a controller view skips the fetch
 * entirely and renders the view with `viewProps = {}` — crashing the page.
 * The actual viewProps are injected via `pageContextInit` from the controller's
 * `renderPage()` call, not via this hook.
 */
function dataFileSource(): string {
  return `// AUTO-GENERATED by @rudderjs/vite — do not edit.
import type { PageContextServer } from 'vike/types'
export const data = (_pageContext: PageContextServer): null => null
`
}

function routeFileSource(view: DiscoveredView): string {
  // CRITICAL: the route URL must match the controller route the user registers
  // (e.g. `Route.get('/home', () => view('home'))`). Vike's client router does
  // its own route table lookup before fetching pageContext.json — if `/home`
  // is not in the table, it falls back to a full page reload. By convention
  // the view id maps to the URL path 1:1: 'home' → /home, 'admin.users' → /admin/users.
  return `// AUTO-GENERATED by @rudderjs/vite — do not edit.
export default '/${view.id.replace(/\./g, '/')}'
`
}

function writeIfChanged(file: string, contents: string): boolean {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  if (fs.existsSync(file)) {
    const existing = fs.readFileSync(file, 'utf8')
    if (existing === contents) return false
  }
  fs.writeFileSync(file, contents)
  return true
}

/**
 * Single shared config at the views root that tells Vike to serialize
 * `viewProps` from server pageContext to the client. Without this, the
 * server SSR works but hydration crashes because the client component
 * receives `props = {}` (viewProps is undefined client-side).
 */
const VIEW_ROOT_CONFIG = `// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Forwards controller-supplied viewProps from server SSR to client hydration.
import type { Config } from 'vike/types'

export default {
  passToClient: ['viewProps'],
} satisfies Config
`

function generate(generatedRoot: string, views: DiscoveredView[]): void {
  if (views.length === 0) return
  writeIfChanged(path.join(generatedRoot, '+config.ts'), VIEW_ROOT_CONFIG)
  for (const v of views) {
    writeIfChanged(path.join(v.outDir, '+Page.tsx'), pageFileSource(v))
    writeIfChanged(path.join(v.outDir, '+route.ts'), routeFileSource(v))
    writeIfChanged(path.join(v.outDir, '+data.ts'),  dataFileSource())
  }
}

function cleanStale(generatedRoot: string, current: DiscoveredView[]): void {
  if (!fs.existsSync(generatedRoot)) return
  const expected = new Set(current.map(v => v.outDir))
  const walkDirs = (dir: string): string[] => {
    const out: string[] = []
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue
      const full = path.join(dir, entry.name)
      // Leaf dirs contain +Page.tsx; non-leaf dirs we recurse into
      if (fs.existsSync(path.join(full, '+Page.tsx'))) {
        out.push(full)
      } else {
        out.push(...walkDirs(full))
      }
    }
    return out
  }
  for (const dir of walkDirs(generatedRoot)) {
    if (!expected.has(dir)) {
      fs.rmSync(dir, { recursive: true, force: true })
    }
  }
}

/**
 * Vite plugin that scans `app/Views/**` and emits virtual Vike pages
 * under `pages/__view/`. Watches the source directory in dev mode.
 */
export function viewsScannerPlugin(): Plugin {
  const cwd            = process.cwd()
  const viewsRoot      = path.join(cwd, 'app', 'Views')
  const pagesRoot      = path.join(cwd, 'pages')
  const generatedRoot  = path.join(pagesRoot, '__view')

  const sync = (): void => {
    const views = discover(viewsRoot, pagesRoot)
    cleanStale(generatedRoot, views)
    generate(generatedRoot, views)
  }

  // Eager sync at plugin construction time — Vike scans `pages/` during its
  // own plugin init, so the generated stubs MUST exist on disk before any
  // Vite/Vike hook fires. configureServer/buildStart are too late.
  if (fs.existsSync(viewsRoot)) sync()

  return {
    name: 'rudderjs:views-scanner',
    enforce: 'pre',
    buildStart() {
      // Re-sync on prod build so the latest views are reflected.
      if (!fs.existsSync(viewsRoot)) return
      sync()
    },
    configureServer(server) {
      if (!fs.existsSync(viewsRoot)) return
      server.watcher.add(viewsRoot)
      const onChange = (file: string): void => {
        if (!file.startsWith(viewsRoot)) return
        if (!VIEW_EXTENSIONS.some(e => file.toLowerCase().endsWith(e))) return
        sync()
      }
      server.watcher.on('add',    onChange)
      server.watcher.on('unlink', onChange)
      server.watcher.on('change', onChange)
    },
  }
}
