// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Keys declared in .env.example → typed Env.get() autocomplete.
// Re-generated on every scan. Keys only your machine's .env carries are
// deliberately absent — .env.example is the committed contract.
declare module '@rudderjs/support' {
  interface EnvRegistry {
    'APP_NAME': string
    'APP_ENV': string
    'APP_DEBUG': string
    'APP_URL': string
    'PORT': string
  }
}
export {}
