export type { RouterLike, RouteHandler } from './types.js'

export { flattenFields, relationName } from './utils.js'
export { buildPanelMiddleware } from './panelMiddleware.js'
export { mountMetaRoutes } from './metaRoutes.js'
export { mountResourceRoutes } from './resourceRoutes.js'
export { mountGlobalRoutes } from './globalRoutes.js'
export { mountVersionRoutes } from './versionRoutes.js'
export { mountDashboardRoutes, buildDefaultLayout } from './dashboardRoutes.js'
export { mountPanelChat } from './panelChat.js'
