/**
 * SHA-256 hash for device-flow tokens stored at rest (RFC 8628 §6.1).
 *
 * `oauth_device_codes.deviceCode` and `userCode` columns hold hex digests, not
 * the plaintext shown to the user. `requestDeviceCode()` is the only place
 * that ever holds the plaintext — it's returned in the response and then
 * forgotten; every subsequent lookup hashes its input first.
 *
 * Plain SHA-256 (no salt, no pepper) is sufficient because both inputs are
 * generated by `randomBytes`/`randomInt` server-side and have enough entropy
 * to make precomputation infeasible:
 *   - `deviceCode` — 32 bytes CSPRNG (256 bits)
 *   - `userCode`   — 8 chars from a 32-symbol alphabet (~40 bits) with a
 *                    15-minute expiry window
 *
 * The 40-bit userCode keyspace IS reachable by an offline attacker who holds
 * a DB dump within the expiry window. The mitigation is operational, not
 * cryptographic: codes expire in 15 minutes, the api-group rate limit puts
 * online brute force out of reach (RFC 8628 §5.2), and the worst-case impact
 * of one hashed userCode being reversed is one approval flow taken over.
 * Apps that want stronger at-rest protection can configure `APP_KEY` and
 * the operator can extend this helper to peppered HMAC — same shape as
 * `client-secret.ts`.
 */
export async function hashDeviceToken(plain: string): Promise<string> {
  const { createHash } = await import('node:crypto')
  return createHash('sha256').update(plain).digest('hex')
}
