// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Forwards controller-supplied viewProps + viewHeaders to client hydration.
import type { Config } from 'vike/types'

export default {
  passToClient: ['viewProps', 'viewHeaders'],
} satisfies Config
