// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Maps view ids → exported component Props types for typed view() calls.
// Re-generated on every scan; views without an exported Props are omitted.
declare module '@rudderjs/view' {
  interface ViewPropsRegistry {
    'demos.typed-view': import('App/Views/Demos/TypedView.tsx').Props
  }
}
export {}
