// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Forwards controller viewProps to client hydration, and wires the RudderJS
// framework hooks via import: strings. RSC can't use physical pages/+<hook>.ts
// stubs — vike-react-rsc-rudder strips them from the client bundle, breaking
// onCreatePageContext (which runs on the client) during hydration. viewHeaders
// stays server-only (read by +headersResponse) — never serialized to the client.
export default {
  passToClient: ['viewProps'],
  onCreatePageContext: 'import:@rudderjs/vite/hooks/onCreatePageContext:onCreatePageContext',
  onError: 'import:@rudderjs/vite/hooks/onError:onError',
  headersResponse: 'import:@rudderjs/vite/hooks/headersResponse:headersResponse',
}
