// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Forwards controller viewProps + viewHeaders to client hydration, and wires
// the RudderJS framework hooks via import: strings. RSC can't use physical
// pages/+<hook>.ts stubs — vike-react-rsc-rudder strips them from the client
// bundle, breaking onCreatePageContext (which runs on the client) during hydration.
export default {
  passToClient: ['viewProps', 'viewHeaders'],
  onCreatePageContext: 'import:@rudderjs/vite/hooks/onCreatePageContext:onCreatePageContext',
  onError: 'import:@rudderjs/vite/hooks/onError:onError',
  headersResponse: 'import:@rudderjs/vite/hooks/headersResponse:headersResponse',
}
