// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Opts this view into Vike's build-time static prerender pipeline.
// Source: `export const prerender = true` in the corresponding app/Views/ file.
export default true
