// AUTO-GENERATED by @rudderjs/vite — overwrite freely to customize.
// Reads response headers off pageContext.viewHeaders (set by view('id', props, { headers })).
export { headersResponse } from '@rudderjs/vite/hooks/headersResponse'
