// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Source: App/Views/Demos/TypedView.tsx
import type { ReactNode } from 'react'
import ViewComponent from 'App/Views/Demos/TypedView.tsx'
import type { Props } from 'App/Views/Demos/TypedView.tsx'
import { usePageContext } from 'vike-react/usePageContext'

// Cast to a permissive component type — controller-supplied props are validated
// at the call site (view('id', props)), not in this generated stub.
const View = ViewComponent as unknown as (props: Props) => ReactNode

export default function Page() {
  const ctx = usePageContext() as unknown as { viewProps?: Props }
  const props = ctx.viewProps ?? ({} as Props)
  return <View {...props} />
}
