import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { Boost } from '../Boost.js'
import type { BoostAgent, SkillEntry } from '../agents/types.js'

// ─── Package Manager Detection ──────────────────────────

interface PackageJson {
  name?: string
  dependencies?: Record<string, string>
  devDependencies?: Record<string, string>
}

function detectPackageManager(cwd: string): 'pnpm' | 'yarn' | 'bun' | 'npx' {
  if (existsSync(join(cwd, 'pnpm-lock.yaml'))) return 'pnpm'
  if (existsSync(join(cwd, 'yarn.lock'))) return 'yarn'
  if (existsSync(join(cwd, 'bun.lockb'))) return 'bun'
  return 'npx'
}

function getMcpCommand(pm: 'pnpm' | 'yarn' | 'bun' | 'npx'): { command: string; args: string[] } {
  const cliPath = 'node_modules/@rudderjs/cli/src/index.ts'

  switch (pm) {
    case 'pnpm':
      return { command: 'pnpm', args: ['exec', 'tsx', cliPath, 'boost:mcp'] }
    case 'yarn':
      return { command: 'yarn', args: ['tsx', cliPath, 'boost:mcp'] }
    case 'bun':
      return { command: 'bunx', args: ['tsx', cliPath, 'boost:mcp'] }
    default:
      return { command: 'npx', args: ['tsx', cliPath, 'boost:mcp'] }
  }
}

// ─── Package Scanning ───────────────────────────────────

function findRudderPackages(cwd: string): string[] {
  const pkgJsonPath = join(cwd, 'package.json')
  if (!existsSync(pkgJsonPath)) return []

  const raw = readFileSync(pkgJsonPath, 'utf-8')
  const pkg: PackageJson = JSON.parse(raw) as PackageJson
  const allDeps = { ...pkg.dependencies, ...pkg.devDependencies }

  return Object.keys(allDeps).filter((name) => name.startsWith('@rudderjs/'))
}

// ─── Guideline & Skill Collection ───────────────────────

interface PackageGuideline {
  packageName: string
  shortName: string
  content: string
}

function collectGuidelines(cwd: string, packages: string[]): PackageGuideline[] {
  const results: PackageGuideline[] = []

  for (const pkg of packages) {
    const guidelinePath = join(cwd, 'node_modules', pkg, 'boost', 'guidelines.md')
    if (existsSync(guidelinePath)) {
      results.push({
        packageName: pkg,
        shortName: pkg.replace('@rudderjs/', ''),
        content: readFileSync(guidelinePath, 'utf-8'),
      })
    }
  }

  return results
}

function collectSkills(cwd: string, packages: string[]): SkillEntry[] {
  const results: SkillEntry[] = []

  for (const pkg of packages) {
    const skillsDir = join(cwd, 'node_modules', pkg, 'boost', 'skills')
    if (!existsSync(skillsDir)) continue

    try {
      const entries = readdirSync(skillsDir, { withFileTypes: true })
      for (const entry of entries) {
        if (entry.isDirectory()) {
          const skillMd = join(skillsDir, entry.name, 'SKILL.md')
          if (existsSync(skillMd)) {
            results.push({
              skillName: entry.name,
              sourcePath: join(skillsDir, entry.name),
            })
          }
        }
      }
    } catch {
      // skip unreadable directories
    }
  }

  return results
}

// ─── Guideline Content Builder ──────────────────────────

function buildGuidelineContent(guidelines: PackageGuideline[]): string {
  if (guidelines.length > 0) {
    const sections = guidelines.map(
      (g) => `## ${g.packageName}\n\n${g.content.trim()}`
    )
    return `# AI Guidelines\n\nAuto-generated by \`boost:install\`. Per-package guidelines from installed @rudderjs/* packages.\n\n${sections.join('\n\n---\n\n')}\n`
  }
  return `# AI Guidelines\n\nAuto-generated by \`boost:install\`.\n\nThis is a RudderJS project — a Laravel-inspired Node.js meta-framework.\nSee https://github.com/rudderjs/rudder for documentation.\n`
}

// ─── Per-Package Guidelines (always written) ────────────

function writePerPackageGuidelines(cwd: string, guidelines: PackageGuideline[]): void {
  if (guidelines.length === 0) return

  const dir = join(cwd, '.ai', 'guidelines')
  mkdirSync(dir, { recursive: true })

  for (const g of guidelines) {
    const dest = join(dir, `${g.shortName}.md`)
    writeFileSync(dest, g.content, 'utf-8')
  }
  console.log(`  Wrote ${guidelines.length} per-package guideline(s) to .ai/guidelines/`)
}

// ─── Agent Selection ────────────────────────────────────

function parseAgentFlag(args?: string[]): string[] | null {
  if (!args) return null
  for (const arg of args) {
    if (arg.startsWith('--agent=')) {
      return arg.slice('--agent='.length).split(',').map(s => s.trim()).filter(Boolean)
    }
  }
  return null
}

function selectAgents(cwd: string, agentNames: string[] | null, allAgents: BoostAgent[]): BoostAgent[] {
  if (agentNames) {
    // Explicit selection via --agent flag
    const selected: BoostAgent[] = []
    for (const name of agentNames) {
      const agent = allAgents.find(a => a.name === name)
      if (agent) {
        selected.push(agent)
      } else {
        console.log(`  Warning: unknown agent "${name}". Available: ${allAgents.map(a => a.name).join(', ')}`)
      }
    }
    return selected
  }

  // Auto-detect: select agents whose config files exist
  const detected = allAgents.filter(a => a.detect(cwd))

  if (detected.length > 0) {
    console.log(`  Detected: ${detected.map(a => a.displayName).join(', ')}`)
    return detected
  }

  // Default to Claude Code if nothing detected
  const claudeCode = allAgents.find(a => a.name === 'claude-code')
  if (claudeCode) {
    console.log('  No agents detected — defaulting to Claude Code')
    return [claudeCode]
  }

  return []
}

// ─── Main Install ───────────────────────────────────────

export interface BoostInstallOptions {
  args?: string[]
}

export async function boostInstall(cwd: string, options?: BoostInstallOptions): Promise<void> {
  console.log('\nBoost: Installing IDE configs for AI coding assistants...\n')

  // 1. Scan packages
  const packages = findRudderPackages(cwd)
  if (packages.length === 0) {
    console.log('  No @rudderjs/* packages found in package.json.')
    return
  }
  console.log(`  Found ${packages.length} @rudderjs/* package(s): ${packages.join(', ')}\n`)

  // 2. Collect guidelines & skills
  const guidelines = collectGuidelines(cwd, packages)
  const skills = collectSkills(cwd, packages)
  const guidelineContent = buildGuidelineContent(guidelines)

  // 3. Select agents
  const allAgents = Boost.getAllAgents()
  const selectedAgents = selectAgents(cwd, parseAgentFlag(options?.args), allAgents)

  if (selectedAgents.length === 0) {
    console.log('  No agents selected.')
    return
  }

  console.log(`  Installing for: ${selectedAgents.map(a => a.displayName).join(', ')}\n`)

  // 4. Detect package manager for MCP command
  const pm = detectPackageManager(cwd)
  const mcpCommand = getMcpCommand(pm)

  // 5. Run each agent's install
  for (const agent of selectedAgents) {
    console.log(`  ${agent.displayName}:`)

    if (agent.supportsGuidelines) {
      await agent.installGuidelines(cwd, guidelineContent)
      console.log(`    ✓ Guidelines`)
    }

    if (agent.supportsMcp) {
      await agent.installMcp(cwd, mcpCommand)
      console.log(`    ✓ MCP config`)
    }

    if (agent.supportsSkills && agent.installSkills && skills.length > 0) {
      await agent.installSkills(cwd, skills)
      console.log(`    ✓ ${skills.length} skill(s)`)
    }
  }

  // 6. Always write per-package guidelines to .ai/guidelines/
  writePerPackageGuidelines(cwd, guidelines)

  // 7. Write boost.json
  const config = {
    version: '0.0.1',
    agents: selectedAgents.map(a => a.name),
    packages,
    generatedAt: new Date().toISOString(),
  }
  writeFileSync(join(cwd, 'boost.json'), JSON.stringify(config, null, 2) + '\n', 'utf-8')
  console.log('  Wrote boost.json')

  console.log('\nDone.\n')
}
